// adapters/pdfExportAdapter.js
// Generate PDF reports for schedules and notes in Synapse Synchrony
// Uses a minimal template-string approach (HTML→PDF via browser or Puppeteer hooks).

/**
 * Build an HTML string for a schedule report.
 * @param {string} userName
 * @param {string} semester
 * @param {object} groupedSlots - { Monday: [...], Tuesday: [...], ... }
 * @returns {string} HTML string
 */
export const buildScheduleHtml = (userName, semester, groupedSlots) => {
    const rows = Object.entries(groupedSlots)
        .filter(([, slots]) => slots.length > 0)
        .map(([day, slots]) => {
            const slotRows = slots
                .map(
                    (s) => `
          <tr>
            <td>${s.startTime} – ${s.endTime}</td>
            <td>${s.subject}</td>
            <td>${s.courseCode ?? '—'}</td>
            <td>${s.room ?? '—'}</td>
            <td>${s.instructor ?? '—'}</td>
          </tr>`
                )
                .join('');
            return `
        <tr class="day-header"><td colspan="5">${day}</td></tr>
        ${slotRows}`;
        })
        .join('');

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Schedule – ${userName}</title>
<style>
  body { font-family: Arial, sans-serif; font-size: 13px; color: #222; }
  h1 { font-size: 20px; } h2 { font-size: 14px; color: #555; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
  th { background: #6d28d9; color: white; }
  tr.day-header td { background: #ede9fe; font-weight: bold; font-size: 14px; }
  tr:nth-child(even) { background: #f9f9f9; }
</style>
</head>
<body>
  <h1>Academic Schedule</h1>
  <h2>${userName} — ${semester}</h2>
  <table>
    <thead><tr><th>Time</th><th>Subject</th><th>Code</th><th>Room</th><th>Instructor</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <p style="color:#888;font-size:11px;margin-top:24px">Generated by Synapse Synchrony on ${new Date().toLocaleDateString()}</p>
</body>
</html>`;
};

/**
 * Build an HTML string for a notes export.
 * @param {string} userName
 * @param {object[]} notes
 */
export const buildNotesHtml = (userName, notes = []) => {
    const noteBlocks = notes
        .map(
            (n) => `
    <div class="note" style="border-left: 4px solid ${n.color ?? '#6d28d9'};">
      <h3>${n.title}</h3>
      <p class="meta">Tags: ${n.tags?.join(', ') || 'None'} | ${new Date(n.updatedAt).toLocaleDateString()}</p>
      <div class="content">${n.content}</div>
    </div>`
        )
        .join('');

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Notes – ${userName}</title>
<style>
  body { font-family: Arial, sans-serif; font-size: 13px; color: #222; }
  h1 { font-size: 20px; }
  .note { margin: 20px 0; padding: 12px 16px; background: #fafafa; border-radius: 4px; }
  .note h3 { margin: 0 0 4px; font-size: 16px; color: #1f1f1f; }
  .meta { font-size: 11px; color: #888; margin-bottom: 8px; }
  .content { font-size: 13px; white-space: pre-wrap; }
  footer { font-size: 11px; color: #aaa; margin-top: 32px; }
</style>
</head>
<body>
  <h1>My Notes</h1>
  <p>Exported by ${userName} on ${new Date().toLocaleDateString()}</p>
  ${noteBlocks}
  <footer>Synapse Synchrony • ${new Date().getFullYear()}</footer>
</body>
</html>`;
};

export default { buildScheduleHtml, buildNotesHtml };
